### PR TITLE
Fix launching with custom arguments

### LINKED ISSUE #225: Selenium Standalone 5.7 does not run
I've got selenium standalone installed as part of Web Component Tester and as of version 5.7 it no longer start successfully as part of a WCT run.

I get the following error:

> Error: Could not create the Java Virtual Machine.
> Error: A fatal exception has occurred. Program will exit.
> Unrecognized option: -port
> 
> Error: Selenium server did not start.Another Selenium process may already be running or your java version may be out of date.

I've reproduced this on both my build's linux docker image (java 7) and locally on my windows dev box (java 8). It didn't occur on my dev box until I reinstalled Selenium to go from 5.6.3 to 5.7.

The issue appears to be caused by commit https://github.com/vvo/selenium-standalone/commit/9f69f35a8984816ab1986dc51c8b74929358e8a6. When I run the java command the way it is constructed now, I get the same error, and when I run it the previous way, selenium starts fine.

### PR DESCRIPTION
**Pull request by stephenash**
```text
$ ./bin/selenium-standalone start -version=2.53.1 -- -port 5556
13:29:49.643 INFO - Launching a standalone Selenium Server
13:29:49.673 INFO - Java: Oracle Corporation 25.45-b02
13:29:49.673 INFO - OS: Mac OS X 10.10.5 x86_64
...
```

```text
$ ./bin/selenium-standalone start -version=3.0.0-beta2 -- -port 5556
13:27:34.467 INFO - Launching a standalone Selenium Server
13:27:34.499 INFO - Java: Oracle Corporation 25.45-b02
13:27:34.499 INFO - OS: Mac OS X 10.10.5 x86_64
...
```

---
Fixes #225

### CODE REVIEW

File: test/programmatic.js [hunk 1]
```diff
@@ -68,6 +68,15 @@ describe('programmatic use', function () {
     });
   });
 
+  it('should start with custom seleniumArgs', function(done) {
+    testStart(done, { seleniumArgs: ['-port', '12345'] }, function(cp) {
+      if (cp.spawnargs && !cp.spawnargs.some(containsChrome)) {
+        done(new Error('Chrome driver should be loaded'));
```
Comment (vvo) [inline test/programmatic.js]: gg!
