### PR TITLE
Fix download urls

### LINKED ISSUE #250: platform is set to 'win64' if process.platform === 'win32' while downloading geckodriver
Could anyone explain the piece of code in https://github.com/vvo/selenium-standalone/blob/master/lib/compute-download-urls.js#L159

> } else if(process.platform === 'win32') {
>     platform = 'win64';
>     type = '.zip';
>   }

why do we set platform = 'win64' if process.platform === 'win32'?

### PR DESCRIPTION
**Pull request by jucrouzet**
Several fixes in download urls (and a little bit of refactoring).

It should fix #250

### CODE REVIEW

File: test/compute-download-urls-test.js [hunk 1]
```diff
@@ -288,6 +339,17 @@ describe('compute-download-urls', function() {
         var actual = computeDownloadUrls(opts);
         assert(actual.firefox.indexOf('macos') > 0);
       });
+
+      it('uses `osx` platform for versions >= 0.6.0', function() {
```
Comment (stephenash) [inline test/compute-download-urls-test.js]: Test name should be `<` or `<=` to match the params?

Comment (jucrouzet) [inline test/compute-download-urls-test.js]: Right, nice spot on this typo. Fixed

**Comment by jucrouzet** [comment]
:tada: !
